/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#1d1b16',
        'surface-container-low': '#f9f3ea',
        'on-surface-variant': '#554337',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        background: '#fff9f0',
        'surface-bright': '#fff9f0',
        'surface-container': '#f3ede4',
        'surface-container-high': '#ede7df',
        'on-tertiary-container': '#50352c',
        'secondary-fixed': '#ffdead',
        'on-primary-fixed-variant': '#703800',
        'on-tertiary-fixed': '#2c160e',
        surface: '#fff9f0',
        'on-tertiary-fixed-variant': '#5d4037',
        'surface-variant': '#e7e2d9',
        'on-primary-fixed': '#301400',
        'secondary-container': '#feba3f',
        'inverse-primary': '#ffb781',
        'on-surface': '#1d1b16',
        'inverse-surface': '#32302a',
        'on-secondary-fixed': '#281900',
        'on-error': '#ffffff',
        'tertiary-container': '#c49d92',
        'primary-fixed-dim': '#ffb781',
        secondary: '#7f5700',
        'on-primary': '#ffffff',
        'surface-tint': '#934b00',
        'surface-container-highest': '#e7e2d9',
        'inverse-on-surface': '#f6f0e7',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#604100',
        'primary-container': '#f28c33',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#6f4c00',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#5f2e00',
        tertiary: '#77574d',
        primary: '#934b00',
        'outline-variant': '#dbc2b1',
        'primary-fixed': '#ffdcc4',
        'secondary-fixed-dim': '#feba3f',
        outline: '#887365',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#e7bdb1',
        'tertiary-fixed': '#ffdbd0',
        'surface-dim': '#dfd9d1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'container-padding-mobile': '20px',
        unit: '8px',
        'container-padding-desktop': '40px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-md': ['Quicksand'],
        'label-sm': ['Quicksand'],
        'label-md': ['Quicksand'],
        'body-lg': ['Quicksand'],
        'headline-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
